Repository JuliaLinearAlgebra/Octavian.jl, pull requests merged in 2020-12, with the labels that each got.

#3 Add some dependencies
  .github/workflows/ci-julia-nightly.yml
  .github/workflows/ci.yml
  Project.toml
  src/Augustus.jl
  src/macros.jl
Labels: dependencies

#6 Initial matmul implementation
  .gitignore
  Project.toml
  src/Octavian.jl
  src/block_sizes.jl
  src/macrokernel.jl
  src/matmul.jl
  src/types.jl
  src/utils.jl
  test/matmul.jl
  test/runtests.jl
Labels: enhancement

#10 Add tests to increase code coverage
  src/Octavian.jl
  src/block_sizes.jl
  src/macrokernels.jl
  src/memory_buffer.jl
  src/pointer_matrix.jl
  src/types.jl
  src/utils.jl
  test/block_sizes.jl
  test/macrokernels.jl
  test/matmul_coverage.jl
  test/pointer_matrix.jl
  test/runtests.jl
  test/test_suite_preamble.jl
  test/utils.jl
Labels: code coverage, test suite

#12 Reorganize the CI workflow files
  .github/workflows/CompatHelper.yml
  .github/workflows/ci-coverage.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  README.md
Labels: continuous integration (ci)

#13 [Docs] Some improvements to the documentation
  docs/Project.toml
  docs/make.jl
  docs/src/internals.md
  docs/src/public-api.md
  src/matmul.jl
Labels: documentation
