Repository JuliaLinearAlgebra/Octavian.jl, pull requests merged in 2021-01, with the labels that each got.

#17 First attempt at multithreading: thread loop 3 only
  .github/workflows/ci-julia-nightly.yml
  .github/workflows/ci.yml
  Project.toml
  src/Octavian.jl
  src/block_sizes.jl
  src/global_constants.jl
  src/init.jl
  src/matmul.jl
  test/init.jl
  test/runtests.jl
Labels: threading

#20 In the README, mention that the package is still experimental
  README.md
Labels: documentation

#21 Temporarily disable CI on Windows
  .github/workflows/ci-julia-nightly.yml
  .github/workflows/ci.yml
Labels: continuous integration (ci)

#26 More descriptive CI job names
  .github/workflows/ci-julia-nightly.yml
  .github/workflows/ci.yml
Labels: continuous integration (ci)

#27 Set the random seed at the beginning of the test suite
  Project.toml
  test/runtests.jl
Labels: test suite

#28 Always use threading
  src/Octavian.jl
  src/macros.jl
  src/matmul.jl
  test/macros.jl
  test/runtests.jl
Labels: threading

#32 [docs] Add a package description
  README.md
  docs/src/index.md
Labels: documentation

#31 Run CI with one thread and three threads
  .github/workflows/ci-julia-nightly.yml
  .github/workflows/ci.yml
Labels: continuous integration (ci), threading

#34 [docs] Add a "Getting Started" page
  README.md
  docs/make.jl
  docs/src/getting-started.md
  docs/src/index.md
  src/Octavian.jl
Labels: documentation

#35 [docs] Remind the user to start Julia with multiple threads
  docs/src/getting-started.md
Labels: documentation

#37 [docs] Fix whitespace
  docs/src/getting-started.md
Labels: documentation

#41 Fast threaded matmul
  .gitignore
  Project.toml
  src/Octavian.jl
  src/block_sizes.jl
  src/funcptrs.jl
  src/global_constants.jl
  src/init.jl
  src/integerdivision.jl
  src/macrokernels.jl
  src/matmul.jl
  src/memory_buffer.jl
  src/pointer_matrix.jl
  src/staticfloats.jl
  src/types.jl
  src/utils.jl
  test/block_sizes.jl
  test/init.jl
  test/macrokernels.jl
  test/matmul.jl
  test/pointer_matrix.jl
  test/runtests.jl
  test/utils.jl
Labels: enhancement

#43 Run CI on Windows
  .github/workflows/ci-julia-nightly.yml
  .github/workflows/ci.yml
Labels: continuous integration (ci)

#44 README: Only mention Tullio.jl and Gaius.jl
  README.md
Labels: documentation

#45 Reorganize the test suite to reduce code duplication
  docs/src/getting-started.md
  test/_matmul.jl
  test/matmul.jl
  test/matmul_coverage.jl
  test/runtests.jl
Labels: code coverage, test suite

#47 Codecov: Add the `codecov.yml` file, and require that coverage never falls below 35%
  codecov.yml
Labels: code coverage

#54 Fix type instability with static sized arrays
  Project.toml
  src/block_sizes.jl
  src/integerdivision.jl
  test/integer_division.jl
  test/runtests.jl
Labels: performance

#53 Codecov: Comment out the "goal" project status
  codecov.yml
Labels: code coverage

#58 Docs: Mention the strengths of Octavian and Tullio respectively
  Project.toml
  README.md
  docs/src/index.md
Labels: documentation
